### ISSUE TITLE
Create PCB Layout

### ISSUE THREAD

**Issue by nbrugger-tgm** [FactoryRally/hardware#2]
## Create a PCB layout for the robots
Use the Schematic as a base
### Tasks
- [ ] Create Gerber file
- [ ] Create *All in one* PDF
- [ ] Create a Layer PDF
- [ ] Create a Documentation PDF
    - Sizing
    - Periferals
### Rules
- Keep it small
- Make it a square or circle
- Provide EasyEDA file
